sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

before_install:
  - gem update --system
  - gem install bundler

cache: bundler
script: bundle exec middleman build
deploy:
  local-dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
